name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login --username AWS --password-stdin <AWS_ECR_URL>

      - name: Build and Push Docker Image
        run: |
          docker build -t <AWS_ECR_URL>/my-app:${{ github.sha }} .
          docker push <AWS_ECR_URL>/my-app:${{ github.sha }}

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/my-app my-app=<AWS_ECR_URL>/my-app:${{ github.sha }}
