name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login --username AWS --password-stdin <253284761052.dkr.ecr.ap-southeast-2.amazonaws.com/my-cicd-flask-app>

      - name: Build and Push Docker Image
        run: |
          docker build -t <253284761052.dkr.ecr.ap-southeast-2.amazonaws.com/my-cicd-flask-app>/my-app:${{ github.sha }} .
          docker push <253284761052.dkr.ecr.ap-southeast-2.amazonaws.com/my-cicd-flask-app>/my-app:${{ github.sha }}

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/my-app my-app=<253284761052.dkr.ecr.ap-southeast-2.amazonaws.com/my-cicd-flask-app>/my-app:${{ github.sha }}
